---
- name: Install Docker and dependencies
  hosts: ubuntu
  become: true
  tasks:
    - name: Remove conflicting packages (containerd)
      apt:
        name: containerd
        state: absent

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

- name: Start the Docker Service in Ubuntu
  tags: prep
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure group docker exists
  tags: prep
  become: true
  group:
    name: docker
    state: present

- name: Adding the current user to the docker group
  tags: prep
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create a docker directory
  file:
    path: /home/marichu/docker_files
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'

- name: Copy Dockerfile to Ubuntu
  become: true
  copy:
    src: /home/marichu/HOA11_MARICHU/Docker/Dockerfile
    dest: /home/marichu/docker_files
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '777'

- name: Build Docker Image
  become: true
  docker_image:
    name: apache-mariadb-image
    tag: latest
    state: present
    source: build
    build:
      path: /home/marichu/docker_files/
      dockerfile: Dockerfile
